workflows:
  windows-desktop-release:
    name: Windows Desktop Release
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      java: 17
      groups:
        - keystore_credentials
    scripts:
      - name: Set up JDK
        script: |
          echo "Using JDK 17"
          
      - name: Build Windows executable
        script: |
          ./gradlew :composeApp:packageDistributionForCurrentOS
          ./gradlew :composeApp:createDistributable
          
      - name: Find artifacts
        script: |
          find composeApp/build/compose/binaries -type f
          
    artifacts:
      - composeApp/build/compose/binaries/**/*
      
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
